import Config

# Configure your database
config :runcom_demo, RuncomDemo.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "runcom_demo_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :runcom_demo, RuncomDemoWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Fm32RCT0zh56o2JyHdypTnbIMWFknUIDFaSesaR/PBUKtix/+jayGj9zql9ONz7J",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:runcom_demo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:runcom_demo, ~w(--watch)]},
    node: ["build.js", "--watch", cd: Path.expand("../../runcom_web/assets", __DIR__)],
    npx: [
      "@tailwindcss/cli",
      "--input", "css/runcom_web.css",
      "--output", "../priv/static/runcom_web.css",
      "--watch",
      cd: Path.expand("../../runcom_web/assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :runcom_demo, RuncomDemoWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # runcom_web built assets
      ~r"runcom_web/priv/static/.*\.(js|css)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/runcom_demo_web/router\.ex$",
      ~r"lib/runcom_demo_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :runcom_demo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Runcom RMQ
config :runcom_demo,
  rmq_connection: "amqp://guest:guest@localhost:5673"
