defmodule Runcom.Remote.ShimGenerator do
  @moduledoc """
  Generates sourceable Bash scripts with function shims.

  The generated script defines Bash functions that call the CLI binary
  to fetch and execute defbash functions from the remote server.

  Note: These scripts use bash features (like process substitution) that
  our parser doesn't support, so we generate raw strings instead of using
  the ~b sigil.
  """

  @doc """
  Generate a Bash script with function shims.

  ## Parameters

  - `cli_name` - Name of the CLI binary (e.g., "myapp")
  - `functions` - Map of namespace => [function_names]

  ## Returns

  A Bash script string that can be sourced.
  """

  @spec generate(String.t(), map()) :: String.t()
  def generate(cli_name, functions) do
    helper = generate_helper(cli_name)
    shims = generate_shims(cli_name, functions)

    """
    #!/bin/bash
    # Generated by #{cli_name} - do not edit
    # Source this file to enable #{cli_name} functions:
    #   source <(#{cli_name} bash-functions)

    #{helper}

    #{shims}
    """
  end

  defp generate_helper(cli_name) do
    """
    __#{cli_name}_call() {
      local namespace="$1"
      local func="$2"
      shift 2

      # Capture shell options
      local errexit=0 pipefail=0
      [[ $- == *e* ]] && errexit=1
      [[ -o pipefail ]] && pipefail=1

      # Capture environment variables as KEY=VALUE lines
      local env_data
      env_data=$(env)

      # Check if stdin is a pipe/file (not terminal)
      if [[ ! -t 0 ]]; then
        #{cli_name} __call "$namespace" "$func" \\
          --errexit="$errexit" \\
          --pipefail="$pipefail" \\
          --env-file=<(printf '%s' "$env_data") \\
          -- "$@"
      else
        #{cli_name} __call "$namespace" "$func" \\
          --errexit="$errexit" \\
          --pipefail="$pipefail" \\
          --env-file=<(printf '%s' "$env_data") \\
          -- "$@" < /dev/null
      fi
    }
    """
  end

  defp generate_shims(cli_name, functions) do
    functions
    |> Enum.flat_map(fn {namespace, func_names} ->
      Enum.map(func_names, fn func_name ->
        generate_shim(cli_name, namespace, func_name)
      end)
    end)
    |> Enum.join("\n")
  end

  defp generate_shim(cli_name, namespace, func_name) do
    "#{namespace}.#{func_name}() { __#{cli_name}_call #{namespace} #{func_name} \"$@\"; }\n"
  end
end
